---
- name: Install the LVM2 packages
  yum: name={{ item }} state=installed
  with_items: lvm_pkgs

- name: Create VG
  lvg: vg={{item.vg}} pvs={{item.pv}} pesize=32 state=present vg_options=--force
  with_items: lvm_create

- name: Create LV
  lvol: vg={{item.vg}} lv={{item.lv}} size=100%FREE
  with_items: lvm_create

- name: Create the ext4 filesystem on lv
  filesystem: fstype=ext4 dev=/dev/{{item.vg}}/{{item.lv}}
  with_items: lvm_create

- name: Create the mount point directory
  file: path={{ item.mount_point }} state=directory
  with_items: lvm_create

- name: Add the mount entry in /etc/fstab
  mount: name={{item.mount_point}} src=/dev/{{item.vg}}/{{item.lv}} state=mounted opts=defaults fstype=ext4
  with_items: lvm_create
